CREATE EXTERNAL TABLE IF NOT EXISTS ${SPP}AGG_TAXI_SERVICE(
	DATE_TAXI DATE,
	SERVICE_TAXI STRING,
	SERVICE_TYPE_IND TINYINT,
	REGION_MANUAL STRING,
	REGION_BS STRING,
	COUNT_TAXI_TRIPS INT)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '${LOCATION}';