CREATE EXTERNAL TABLE IF NOT EXISTS ${SPP}STG_TAXI_USER_ACTIVITY(
	DATE_TAXI DATE,
	SUBS_NUM STRING,
	SERVICE_TAXI STRING,
	REGION_MANUAL STRING,
	REGION_BS STRING,
	SERVICE_TYPE_IND TINYINT,
	TAXI_DRIVER_FCT TINYINT,
	COUNT_TAXI_TRIPS INT)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t'
STORED AS TEXTFILE
LOCATION '${LOCATION}';