ALTER TABLE ${DIGITAL}DIM_WEB_ENTITY
ADD IF NOT EXISTS PARTITION(EXPIRATION_DATE="${EXPIRATION_DATE}")
LOCATION '${INPUT_DIR}';
ALTER TABLE ${DIGITAL}DIM_WEB_ENTITY
ADD IF NOT EXISTS PARTITION(EXPIRATION_DATE="${DATE_OPENED}")
LOCATION '${INPUT_OPENED_DIR}';