CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_PRODUCT(
	ID DOUBLE,
	TYPE STRING,
	MARKETING_PRODUCT_ID STRING,
	IS_ARCHIVE INT,
	IS_DEL INT,
	EFFECTIVE_DATE DATE)
PARTITIONED BY (EXPIRATION_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS TEXTFILE
LOCATION '${LOCATION}';