CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}AGG_PRODUCT_REGION_LINK(
	PRODUCT_ID DOUBLE,
	REGION_ID DOUBLE,
	EFFECTIVE_DATE STRING,
	EXPIRATION_DATE STRING)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';