CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}AGG_WEB_ENTITY(
	ENTITYID DOUBLE,
	PRODUCT_ID DOUBLE,
	SOC STRING,
	ENTITY_TYPE STRING,
	BUSINESS_TYPE STRING,
	PAY_SYSTEM_TYPE STRING,
	TITLE STRING,
	EFFECTIVE_DATE STRING,
	EXPIRATION_DATE STRING)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';