CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_PRODUCT(
	ID DOUBLE,
	TYPE STRING,
	MARKETING_PRODUCT_ID STRING,
	IS_ARCHIVE BOOLEAN,
	IS_DEL BOOLEAN,
	EFFECTIVE_DATE STRING,
	EXPIRATION_DATE STRING)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';