CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_REGION(
	ID DOUBLE,
	TITLE STRING,
	EFFECTIVE_DATE DATE)
PARTITIONED BY (EXPIRATION_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';