CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_WEB_ENTITY(
	ENTITYID DOUBLE,
	SOC STRING,
	ENTITY_TYPE STRING,
	BUSINESS_TYPE STRING,
	PAY_SYSTEM_TYPE STRING,
	TITLE STRING,
	EFFECTIVE_DATE DATE)
PARTITIONED BY (EXPIRATION_DATE DATE)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';