CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_EXTERNAL_REGION_MAPPING(
	REGION_ID DOUBLE,
	ID DOUBLE,
	SYSTEM_NAME STRING,
	VALUE STRING,
	EFFECTIVE_DATE STRING,
	EXPIRATION_DATE STRING)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';