CREATE EXTERNAL TABLE IF NOT EXISTS ${DIGITAL}DIM_REGION(
	ID DOUBLE,
	TITLE STRING,
	EFFECTIVE_DATE STRING,
	EXPIRATION_DATE STRING)
PARTITIONED BY (TIME_KEY STRING)
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\u0001'
STORED AS SEQUENCEFILE
LOCATION '${LOCATION}';